### ISSUE TITLE
Build instructions / Compiled release

### ISSUE THREAD

**Issue by rjsg42** [marty28/XBMC-360#3]
Hi, first of all thanks for this amazing project! I want to test the new implemented SMB capabilities but i can't find build instructions or a compiled release.

Could you share it?

Thanks a lot!

**Comment by marty28** [comment]
Hi,

Sorry for the late reply, I have ported the LibSMB2 library but it's not yet usable from the UI, I have hardcoded tests with it and it works well. But now we have media sources working in my recent update my next focus is getting it working through the UI.

A new build with working media sources can be downloaded here:
https://drive.google.com/file/d/180zj6LYp5p4hlPaH4ZbYpiW614zKXvN7/view

Thanks

**Comment by rjsg42** [comment]
Thanks!! I will try it this weekend

**Comment by marty28** [comment]
No worries, you will prob find the player is quite picky with file types and missing codecs. My next big focus after getting SMB streaming finished is a huge update to the player.
