### ISSUE TITLE
Libsmb2 it's not compiling on visual studio 2010

### ISSUE THREAD

**Issue by wolfysdl** [marty28/XBMC-360#4]
I tried to compile xbmc-360 yesterday and it compiles but the libsm2 does not compile properly, do you have any plans to solve this?

**Comment by marty28** [comment]
Hey,

It compiles fine for me, what errors are you getting?

Working well and can stream movies, I just need to finish the GUI to map drives.

Regards

**Comment by wolfysdl** [comment]
> Hey,
> 
> It compiles fine for me, what errors are you getting?
> 
> Working well and can stream movies, I just need to finish the GUI to map drives.
> 
> Regards

i was getting this one now since i recompiled it
![Screenshot_4](https://user-images.githubusercontent.com/75867486/159161717-f580871a-6a96-405f-a895-9aa7d57824ad.png)

**Comment by marty28** [comment]
That is not a real compiler error, that is saying it can't connect to an Xbox 360 Dev Kit after the build finished to transfer the binary/XEX onto it for testing.

This is not an issue, you can just copy the XEX file from the Release folder onto your modded Xbox 360 along with the other files it needs to run.

Thanks

**Comment by wolfysdl** [comment]
Ok 

> That is not a real compiler error, that is saying it can't connect to an Xbox 360 Dev Kit after the build finished to transfer the binary/XEX onto it for testing.
> 
> This is not an issue, you can just copy the XEX file from the Release folder onto your modded Xbox 360 along with the other files it needs to run.
> 
> Thanks

Ok, so it's a false positive thanks
